#!/bin/sh
set -Cefu

main="$AUTOPKGTEST_TMP/main"
cat > "$main.cpp" <<EOF
#include <stdio.h>
#include <eXaDrums.h>
int main () {
    printf ("%s\n", eXaDrumsApi::LIBEXADRUMS_VERSION);
    return 0;
}
EOF
g++ "$main.cpp" -o "$main" `pkg-config --cflags --libs exadrums`
"$main"
