Document: libexadrums
Title: Debian libexadrums Manual
Author: <insert document author here>
Abstract: This manual describes what libexadrums is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libexadrums/libexadrums.sgml.gz

Format: postscript
Files: /usr/share/doc/libexadrums/libexadrums.ps.gz

Format: text
Files: /usr/share/doc/libexadrums/libexadrums.text.gz

Format: HTML
Index: /usr/share/doc/libexadrums/html/index.html
Files: /usr/share/doc/libexadrums/html/*.html
